[[multichain]]
chainID = 1
name = "Ethereum mainnet"
# Private gateway endpoint recommended
gateway = "https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
blkinterval = 15
blkdelay = 8
forwardblkdelay = 5
cbridge = "0x5427FEFA711Eff984124bFBB1AB6fbf5E3DA1820"
otvault = "0xB37D31b2A74029B5951a2778F959282E2D518595"
otvault2 = "0x7510792A3B1969F9307F3845CE88e39578f2bAE1"
ptbridge = "0x16365b45EB269B5B5dACB34B4a15399Ec79b95eB"
ptbridge2 = "0x52E4f244f380f8fA51816c8a10A63105dd4De084"
msgbus = "0x4066d196a423b2b3b8b054f4f40efb47a74e200c"
wdinbox = "0xD20fc42E293734f58316E2106933B8D9FB14F5b2"
farmingrewards = "0x61f85fF2a2f4289Be4bb9B72Fc7010B3142B5f41"
xferagt = "0x9b274BC73940d92d0Af292Bde759cbFCCE661a0b"
maxfeepergasgwei = 500
addgasestimateratio = 0.6

[[multichain]]
chainID = 56
name = "BSC"
# Private gateway endpoint recommended
gateway = "https://bsc-dataseed.binance.org"
blkinterval = 15
blkdelay = 20
forwardblkdelay = 50
maxblkdelta = 5000
cbridge = "0xdd90E5E87A2081Dcf0391920868eBc2FFB81a1aF"
otvault = "0x78bc5Ee9F11d133A08b331C2e18fE81BE0Ed02DC"
otvault2 = "0x11a0c9270D88C99e221360BCA50c2f6Fda44A980"
ptbridge = "0xd443FE6bf23A4C9B78312391A30ff881a097580E"
ptbridge2 = "0x26c76F7FeF00e02a5DD4B5Cc8a0f717eB61e1E4b"
msgbus = "0x95714818fdd7a5454f73da9c777b3ee6ebaeea6b"
wdinbox = "0xf0FF9888A70f44eb12223A6a55C65976BA7bf854"
xferagt = "0x3d85B598B734a0E7c8c1b62B00E972e9265dA541"
addgasgwei = 2
mingasgwei = 5
addgasestimateratio = 0.3

[[multichain]]
chainID = 42161
name = "Arbitrum"
# Private gateway endpoint recommended
gateway = "https://arb1.arbitrum.io/rpc"
blkinterval = 10
blkdelay = 1
forwardblkdelay = 500
maxblkdelta = 99999
cbridge = "0x1619DE6B6B20eD217a58d00f37B9d47C7663feca"
otvault = "0xFe31bFc4f7C9b69246a6dc0087D91a91Cb040f76"
otvault2 = "0xEA4B1b0aa3C110c55f650d28159Ce4AD43a4a58b"
ptbridge = "0xbdd2739AE69A054895Be33A22b2D2ed71a1DE778"
ptbridge2 = "0xc72e7fC220e650e93495622422F3c14fb03aAf6B"
msgbus = "0x3ad9d0648cdaa2426331e894e980d0a5ed16257f"
wdinbox = "0xfe0401bFFBeECE5d9FaE7f1b9a8f1e03FA1c3184"
addgasestimateratio = 0.3

[[multichain]]
chainID = 137
name = "Polygon"
# Private gateway endpoint recommended
gateway = "https://polygon-rpc.com"
blkinterval = 15
blkdelay = 200
forwardblkdelay = 50
maxblkdelta = 5000
cbridge = "0x88DCDC47D2f83a99CF0000FDF667A468bB958a78"
otvault = "0xc1a2D967DfAa6A10f3461bc21864C23C1DD51EeA"
otvault2 = "0x4C882ec256823eE773B25b414d36F92ef58a7c0C"
ptbridge = "0x4d58FDC7d0Ee9b674F49a0ADE11F26C3c9426F7A"
ptbridge2 = "0xb51541df05DE07be38dcfc4a80c05389A54502BB"
msgbus = "0xaFDb9C40C7144022811F034EE07Ce2E110093fe6"
wdinbox = "0x0E6847e732c0dfE40cc15216AC95E558960e522e"
addgasestimateratio = 0.3

[[multichain]]
chainID = 43114
name = "Avalanche"
# Private gateway endpoint recommended
gateway = "https://rpc.ankr.com/avalanche"
# gateway = "https://api.avax.network/ext/bc/C/rpc"
blkinterval = 15
blkdelay = 15
forwardblkdelay = 50
maxblkdelta = 3000
cbridge = "0xef3c714c9425a8F3697A9C969Dc1af30ba82e5d4"
otvault = "0x5427FEFA711Eff984124bFBB1AB6fbf5E3DA1820"
otvault2 = "0xb51541df05DE07be38dcfc4a80c05389A54502BB"
ptbridge = "0x88DCDC47D2f83a99CF0000FDF667A468bB958a78"
ptbridge2 = "0xb774C6f82d1d5dBD36894762330809e512feD195"
msgbus = "0x5a926eeeafc4d217add17e9641e8ce23cd01ad57"
wdinbox = "0x03ab38cF52173CC71be33B0D2779568f412Be828"
addgasestimateratio = 0.3

[[multichain]]
chainID = 250
name = "Fantom"
# Private gateway endpoint recommended
gateway = "https://rpc.ftm.tools"
blkinterval = 10
blkdelay = 30
maxblkdelta = 10000
forwardblkdelay = 80
cbridge = "0x374B8a9f3eC5eB2D97ECA84Ea27aCa45aa1C57EF"
otvault = "0x7D91603E79EA89149BAf73C9038c51669D8F03E9"
ptbridge = "0x38D1e20B0039bFBEEf4096be00175227F8939E51"
ptbridge2 = "0x30F7Aa65d04d289cE319e88193A33A8eB1857fb9"
msgbus = "0xFF4E183a0Ceb4Fa98E63BbF8077B929c8E5A2bA4"
addgasgwei = 10
addgasestimateratio = 0.3

[[multichain]]
chainID = 10
name = "Optimism"
# Private gateway endpoint recommended
gateway = "https://mainnet.optimism.io"
blkinterval = 10
blkdelay = 1
forwardblkdelay = 50
maxblkdelta = 10000
cbridge = "0x9D39Fc627A6d9d9F8C831c16995b209548cc3401"
otvault = "0xbCfeF6Bb4597e724D720735d32A9249E0640aA11"
ptbridge = "0x61f85fF2a2f4289Be4bb9B72Fc7010B3142B5f41"
ptbridge2 = "0xC3c5B9474273113efB74e7Da43B5AAba0Cd9699A"
msgbus = "0x0D71D18126E03646eb09FEc929e2ae87b7CAE69d"
wdinbox = "0x1b6a49B01176020b153d0cD5Bc90Ef2b75676F00"
farmingrewards = "0x06292DE88aDb3b1557B034ebB1c367E65Ab93E4C"
addgasestimateratio = 0.3

[[multichain]]
chainID = 288
name = "Boba"
gateway = "https://mainnet.boba.network/"
blkinterval = 10
blkdelay = 1
forwardblkdelay = 500
maxblkdelta = 10000
cbridge = "0x841ce48F9446C8E281D3F1444cB859b4A6D0738C"
otvault = "0x8db213bE5268a2b8B78Af08468ff1EA422073Da0"
otvault2 = "0x4C882ec256823eE773B25b414d36F92ef58a7c0C"
ptbridge = "0xC5Ef662b833De914B9bA7a3532C6BB008a9b23a6"
addgasestimateratio = 0.3

[[multichain]]
chainID = 1666600000
name = "Harmony"
gateway = "https://harmony-0-rpc.gateway.pokt.network"
# gateway = "https://api.fuzz.fi"
blkinterval = 10
blkdelay = 15
forwardblkdelay = 500
maxblkdelta = 1024
cbridge = "0x78a21c1d3ed53a82d4247b9ee5bf001f4620ceec"
ptbridge = "0xdd90e5e87a2081dcf0391920868ebc2ffb81a1af"
maxgasgwei = 30
addgasestimateratio = 0.3
proxyport = 10300

[[multichain]]
chainID = 42220
name = "Celo"
gateway = "https://forno.celo.org"
blkinterval = 10
blkdelay = 10
forwardblkdelay = 100
maxblkdelta = 10000
cbridge = "0xBB7684Cc5408F4DD0921E5c2Cadd547b8f1AD573"
otvault = "0xD9d1034ef3d21221F008C7e96346CA999966752C"
ptbridge = "0xDA1DD66924B0470501aC7736372d4171cDd1162E"
addgasestimateratio = 0.3
proxyport = 10301

[[multichain]]
chainID = 1088
name = "Metis Andromeda Mainnet"
gateway = "https://andromeda.metis.io/?owner=1088"
blkinterval = 15
blkdelay = 1
forwardblkdelay = 50
maxblkdelta = 10000
cbridge = "0x841ce48F9446C8E281D3F1444cB859b4A6D0738C"
ptbridge = "0x3bbaDFf9aeee4a74D3Cf6da05C30868C9Ff85BB8"
ptbridge2 = "0xb3833Ecd19D4Ff964fA7bc3f8aC070ad5e360E56"
addgasestimateratio = 0.3

[[multichain]]
chainID = 1313161554
name = "Aurora MainNet"
gateway = "https://mainnet.aurora.dev"
blkinterval = 15
blkdelay = 30
forwardblkdelay = 200
maxblkdelta = 10000
cbridge = "0x841ce48F9446C8E281D3F1444cB859b4A6D0738C"
otvault2 = "0xbCfeF6Bb4597e724D720735d32A9249E0640aA11"
ptbridge = "0x4384d5a9D7354C65cE3aee411337bd40493Ad1bC"
ptbridge2 = "0xbdd2739AE69A054895Be33A22b2D2ed71a1DE778"
msgbus = "0xc1a2D967DfAa6A10f3461bc21864C23C1DD51EeA"
addgasestimateratio = 0.3

[[multichain]]
chainID = 1285
name = "Moonriver"
gateway = "https://rpc.api.moonriver.moonbeam.network"
blkinterval = 20
blkdelay = 6
forwardblkdelay = 200
maxblkdelta = 10000
cbridge = "0x841ce48F9446C8E281D3F1444cB859b4A6D0738C"
ptbridge = "0x374B8a9f3eC5eB2D97ECA84Ea27aCa45aa1C57EF"
ptbridge2 = "0x0D71D18126E03646eb09FEc929e2ae87b7CAE69d"
msgbus = "0x940dAAbA3F713abFabD79CdD991466fe698CBe54"
addgasestimateratio = 0.3
maxpriorityfeepergasgwei = 1

[[multichain]]
chainID = 100
name = "xDai"
gateway = "https://rpc.gnosischain.com"
# gateway = "https://xdai.poanetwork.dev"
blkinterval = 15
blkdelay = 10
forwardblkdelay = 200
maxblkdelta = 10000
cbridge = "0x3795C36e7D12A8c252A20C5a7B455f7c57b60283"
ptbridge = "0xd4c058380D268d85bC7c758072f561e8f2dB5975"
addgasestimateratio = 0.3

[[multichain]]
chainID = 66
name = "OEC"
gateway = "https://exchainrpc.okex.org"
blkinterval = 15
blkdelay = 10
forwardblkdelay = 200
maxblkdelta = 2000
cbridge = "0x6a2d262D56735DbA19Dd70682B39F6bE9a931D98"
ptbridge = "0x48284Eb583a1F3058F4BCe0a685D44FE29d4539e"
ptbridge2 = "0x8bCcdD21B97733D78a4168be1D6049A45652C4B8"
addgasestimateratio = 0.3

[[multichain]]
chainID = 128
name = "Heco"
gateway = "https://http-mainnet.hecochain.com"
blkinterval = 15
blkdelay = 12
forwardblkdelay = 200
maxblkdelta = 5000
cbridge = "0xBB7684Cc5408F4DD0921E5c2Cadd547b8f1AD573"
otvault = "0x5d96d4287D1ff115eE50faC0526cf43eCf79bFc6"
ptbridge = "0x81ECac0D6Be0550A00FF064a4f9dd2400585FE9c"
addgasestimateratio = 0.3

[[multichain]]
chainID = 42262
name = "OASIS"
gateway = "https://emerald.oasis.dev"
blkinterval = 30
blkdelay = 8
forwardblkdelay = 50
maxblkdelta = 100
cbridge = "0x841ce48F9446C8E281D3F1444cB859b4A6D0738C"
ptbridge = "0xBB7684Cc5408F4DD0921E5c2Cadd547b8f1AD573"
ptbridge2 = "0x3b53D2C7B44d40BE05Fa5E2309FFeB6eB2492d88"
addgasgwei = 10
addgasestimateratio = 0.3

[[multichain]]
chainID = 1284
name = "Moonbeam"
gateway = "https://rpc.api.moonbeam.network"
blkinterval = 20
blkdelay = 6
forwardblkdelay = 200
maxblkdelta = 10000
cbridge = "0x841ce48F9446C8E281D3F1444cB859b4A6D0738C"
ptbridge = "0xBB7684Cc5408F4DD0921E5c2Cadd547b8f1AD573"
ptbridge2 = "0x3b53D2C7B44d40BE05Fa5E2309FFeB6eB2492d88"
addgasestimateratio = 0.3
maxpriorityfeepergasgwei = 1

[[multichain]]
chainID = 592
name = "Astar"
gateway = "https://astar.api.onfinality.io/public"
blkinterval = 30
blkdelay = 6
forwardblkdelay = 200
maxblkdelta = 10000
cbridge = "0x841ce48F9446C8E281D3F1444cB859b4A6D0738C"
otvault = "0xbCfeF6Bb4597e724D720735d32A9249E0640aA11"
otvault2 = "0x243F56Bad0170a6c050a91925245AD8360350108"
ptbridge = "0xBB7684Cc5408F4DD0921E5c2Cadd547b8f1AD573"
ptbridge2 = "0x3b53D2C7B44d40BE05Fa5E2309FFeB6eB2492d88"
msgbus = "0xf5C6825015280CdfD0b56903F9F8B5A2233476F5"
addgasestimateratio = 0.3
maxpriorityfeepergasgwei = 3
proxyport = 10304

[[multichain]]
chainID = 57
name = "Syscoin"
gateway = "https://rpc.syscoin.org"
blkinterval = 60
blkdelay = 1
maxblkdelta = 10000
forwardblkdelay = 10
cbridge = "0x841ce48f9446c8e281d3f1444cb859b4a6d0738c"
otvault = "0x1E6b1ceAF75936f153ABB7B65FBa57AbaE14e6CE"
ptbridge = "0xBB7684Cc5408F4DD0921E5c2Cadd547b8f1AD573"
msgbus = "0xf5C6825015280CdfD0b56903F9F8B5A2233476F5"
addgasestimateratio = 0.3

[[multichain]]
chainID = 336
name = "ShidenNetworkMainnet"
# gateway = "https://shiden.api.onfinality.io/public"
gateway = "https://evm.shiden.astar.network"
blkinterval = 20
blkdelay = 6
maxblkdelta = 300
forwardblkdelay = 100
cbridge = "0x841ce48F9446C8E281D3F1444cB859b4A6D0738C"
otvault = "0xBB7684Cc5408F4DD0921E5c2Cadd547b8f1AD573"
addgasestimateratio = 0.3
maxpriorityfeepergasgwei = 3
proxyport = 10305

[[multichain]]
chainID = 2001
name = "Milkomeda Cardano"
gateway = "https://rpc-mainnet-cardano-evm.c1.milkomeda.com"
blkinterval = 20
blkdelay = 15
maxblkdelta = 10000
forwardblkdelay = 10
cbridge = "0x841ce48f9446c8e281d3f1444cb859b4a6d0738c"
otvault2 = "0xb51541df05DE07be38dcfc4a80c05389A54502BB"
ptbridge = "0xBB7684Cc5408F4DD0921E5c2Cadd547b8f1AD573"
ptbridge2 = "0x3b53D2C7B44d40BE05Fa5E2309FFeB6eB2492d88"
msgbus = "0x81c548584189ba1d54510313d3b5e601f6679818"
addgasestimateratio = 0.3

[[multichain]]
chainID = 9001
name = "Evmos"
gateway = "https://evmos-json-rpc.stakely.io"
# gateway = "https://eth.bd.evmos.org:8545"
blkinterval = 30
blkdelay = 15
maxblkdelta = 10000
forwardblkdelay = 200
cbridge = "0x5F52B9d1C0853da636e178169e6B426E4cCfA813"
ptbridge = "0x5427FEFA711Eff984124bFBB1AB6fbf5E3DA1820"
ptbridge2 = "0xC1d6E421a062Fdbb26C31Db4a2113dF0F678CD04"
addgasestimateratio = 0.3

[[multichain]]
chainID = 1024
name = "Clover"
gateway = "https://api-para.clover.finance"
blkinterval = 30
blkdelay = 15
maxblkdelta = 10000
forwardblkdelay = 200
cbridge = "0x841ce48F9446C8E281D3F1444cB859b4A6D0738C"
ptbridge = "0xBB7684Cc5408F4DD0921E5c2Cadd547b8f1AD573"
ptbridge2 = "0x3b53D2C7B44d40BE05Fa5E2309FFeB6eB2492d88"
addgasestimateratio = 0.3
maxpriorityfeepergasgwei = 1
proxyport = 10306
gaslimit = 500000

[[multichain]]
chainID = 47805
name = "REI Network"
gateway = "https://rpc.rei.network"
blkinterval = 30
blkdelay = 15
forwardblkdelay = 100
maxblkdelta = 10000
cbridge = "0x841ce48F9446C8E281D3F1444cB859b4A6D0738C"
ptbridge = "0xBB7684Cc5408F4DD0921E5c2Cadd547b8f1AD573"
ptbridge2 = "0x9B36f165baB9ebe611d491180418d8De4b8f3a1f"
addgasestimateratio = 0.3

[[multichain]]
chainID = 1030
name = "Conflux"
gateway = "https://evm.confluxrpc.com"
blkinterval = 25
blkdelay = 20
forwardblkdelay = 50
maxblkdelta = 100
cbridge = "0x841ce48F9446C8E281D3F1444cB859b4A6D0738C"
ptbridge = "0xBB7684Cc5408F4DD0921E5c2Cadd547b8f1AD573"
ptbridge2 = "0x3b53D2C7B44d40BE05Fa5E2309FFeB6eB2492d88"
addgasestimateratio = 0.3
proxyport = 10307

[[multichain]]
chainID = 12340001
name = "Flow Mainnet"
gateway = "access.mainnet.nodes.onflow.org:9000"
blkinterval = 0
blkdelay = 0
maxblkdelta = 240
cbridge = "08dd120226ec2213"
otvault = "08dd120226ec2213"
ptbridge = "08dd120226ec2213"

[[multichain]]
chainID = 44
name = "Crab Mainnet"
gateway = "https://crab-rpc.darwinia.network"
blkinterval = 30
blkdelay = 8
maxblkdelta = 5000
cbridge = "0x841ce48F9446C8E281D3F1444cB859b4A6D0738C"
ptbridge = "0xBB7684Cc5408F4DD0921E5c2Cadd547b8f1AD573"
ptbridge2 = "0x3b53D2C7B44d40BE05Fa5E2309FFeB6eB2492d88"
proxyport = 10308

[[multichain]]
chainID = 210425
name = "PlatON"
gateway = "https://openapi2.platon.network/rpc"
blkinterval = 30
blkdelay = 60
forwardblkdelay = 100
maxblkdelta = 10000
cbridge = "0xBf2B2757F0B2a2f70136C4A6627e99d8ec5cC7b9"
ptbridge = "0x31d95c7fc6b5520B4BdCD78Efa689dD1CCa5741E"
ptbridge2 = "0xD340BC3Ec35e63BcF929C5A9ad3AE5B1EBDbE678"
proxyport = 10309

[[multichain]]
chainID = 73772
name = "Swimmer Network"
gateway = "https://avax-cra-rpc.gateway.pokt.network/"
blkinterval = 30
blkdelay = 4
forwardblkdelay = 100
maxblkdelta = 10000
cbridge = "0xb51541df05DE07be38dcfc4a80c05389A54502BB"
ptbridge2 = "0xF8Bf9988206c4de87F52A3c24486E4367B7088CB"
addgasestimateratio = 0.3

[[multichain]]
chainID = 416
name = "SX Network"
gateway = "https://rpc.sx.technology"
blkinterval = 30
blkdelay = 20
forwardblkdelay = 100
maxblkdelta = 10000
cbridge = "0x9B36f165baB9ebe611d491180418d8De4b8f3a1f"
ptbridge2 = "0x9Bb46D5100d2Db4608112026951c9C965b233f4D"
addgasestimateratio = 0.3
proxyport = 10310

[[multichain]]
chainID = 16350
name = "Ape Chain"
gateway = "https://bas.metaapesgame.com/bas_mainnet_full_rpc"
blkinterval = 15
blkdelay = 10
forwardblkdelay = 100
maxblkdelta = 5000
cbridge = "0x9B36f165baB9ebe611d491180418d8De4b8f3a1f"
otvault2 = "0x9Bb46D5100d2Db4608112026951c9C965b233f4D"
msgbus = "0x5471ea8f739dd37E9B81Be9c5c77754D8AA953E4"

[[multichain]]
chainID = 2222
name = "Kava EVM Co-Chain"
gateway = "https://evm.kava.io"
blkinterval = 30
forwardblkdelay = 100
blkdelay = 15
maxblkdelta = 10000
cbridge = "0xb51541df05DE07be38dcfc4a80c05389A54502BB"
ptbridge2 = "0xF8Bf9988206c4de87F52A3c24486E4367B7088CB"

[[multichain]]
chainID = 58
name = "Ontology EVM"
gateway = "https://dappnode10.ont.io:10339"
blkinterval = 30
blkdelay = 2
maxblkdelta = 10000
forwardblkdelay = 100
cbridge = "0x841ce48F9446C8E281D3F1444cB859b4A6D0738C"
ptbridge2 = "0xd4c058380D268d85bC7c758072f561e8f2dB5975"
proxyport = 10311

[[multichain]]
chainID = 71402
name = "NERVOS EVM"
gateway = "https://v1.mainnet.godwoken.io/rpc"
blkinterval = 30
blkdelay = 1
maxblkdelta = 10000
forwardblkdelay = 200
cbridge = "0x4C882ec256823eE773B25b414d36F92ef58a7c0C"
ptbridge2 = "0xb3833Ecd19D4Ff964fA7bc3f8aC070ad5e360E56"
proxyport = 10312

[[multichain]]
chainID = 8217
name = "Klaytn"
gateway = "https://public-node-api.klaytnapi.com/v1/cypress"
blkinterval = 30
blkdelay = 30
maxblkdelta = 10000
forwardblkdelay = 200
cbridge = "0x4C882ec256823eE773B25b414d36F92ef58a7c0C"
ptbridge2 = "0xb3833Ecd19D4Ff964fA7bc3f8aC070ad5e360E56"

[[multichain]]
chainID = 42170
name = "Arbitrum Nova"
gateway = "https://nova.arbitrum.io/rpc"
blkinterval = 10
blkdelay = 4
maxblkdelta = 10000
forwardblkdelay = 500
cbridge = "0xb3833Ecd19D4Ff964fA7bc3f8aC070ad5e360E56"
ptbridge2 = "0xa55C7E1274bE5db2275a0BDd055f81e8263b7954"
msgbus = "0xf5C6825015280CdfD0b56903F9F8B5A2233476F5"

[[multichain]]
chainID = 2002
name = "Milkomeda A1 Mainnet"
gateway = "https://rpc-mainnet-algorand-rollup.a1.milkomeda.com"
blkinterval = 30
blkdelay = 1
maxblkdelta = 5000
cbridge = "0xa7C9FeDe809b6af10dC52590804c69F40f6f8154"
ptbridge2 = "0x422849B355039bC58F2780cc4854919fC9cfaF94"
addgasgwei = 20

[[multichain]]
chainID = 73
name = "FNCY Chain"
gateway = "https://fncy-seed1.fncy.world"
blkinterval = 15
blkdelay = 5
forwardblkdelay = 100
maxblkdelta = 1000
cbridge = "0x9B36f165baB9ebe611d491180418d8De4b8f3a1f"
otvault2 = "0x9Bb46D5100d2Db4608112026951c9C965b233f4D"
ptbridge2 = "0xf5C6825015280CdfD0b56903F9F8B5A2233476F5"

[[multichain]]
chainID = 248
name = "Oasys Mainnet"
gateway = "https://rpc.mainnet.oasys.games/"
blkinterval = 15
blkdelay = 4
forwardblkdelay = 200
maxblkdelta = 10000
cbridge = "0x5200000000000000000000000000000000000015"
ptbridge2 = "0x5200000000000000000000000000000000000017"

[[multichain]]
chainID = 12360001
name = "aptos"
gateway = "127.0.0.1:7799"
blkinterval = 15
blkdelay = 1
maxblkdelta = 100
cbridge = "8d87a65ba30e09357fa2edea2c80dbac296e5dec2b18287113500b902942929d"
otvault2 = "8d87a65ba30e09357fa2edea2c80dbac296e5dec2b18287113500b902942929d"
ptbridge2 = "8d87a65ba30e09357fa2edea2c80dbac296e5dec2b18287113500b902942929d"

[[multichain]]
chainID = 13000
name = "SPS Mainnet"
gateway = "https://rpc.ssquad.games"
blkinterval = 30
blkdelay = 15
forwardblkdelay = 300
maxblkdelta = 5000
cbridge = "0x3b53d2c7b44d40be05fa5e2309ffeb6eb2492d88"
otvault2 = "0x51AF61B7026a0aE369acc8652Ab2fb637F4689F7"
msgbus = "0xf5C6825015280CdfD0b56903F9F8B5A2233476F5"

[[multichain]]
chainID = 324
name = "zkSync Era Mainnet"
gateway = "https://zksync2-mainnet.zksync.io"
blkinterval = 30
blkdelay = 0
forwardblkdelay = 300
maxblkdelta = 5000
cbridge = "0x54069e96C4247b37C2fbd9559CA99f08CD1CD66c"
ptbridge2 = "0x0D72Be73619e29A67fbD28348AC952288CC9ee46"
msgbus = "0xeC778A485247b2E863e0D53660761EA602c8a51D"

[[multichain]]
chainID = 23294
name = "Oasis Sapphire"
gateway = "https://sapphire.oasis.io"
blkinterval = 30
blkdelay = 15
forwardblkdelay = 200
maxblkdelta = 5000
cbridge = "0x9B36f165baB9ebe611d491180418d8De4b8f3a1f"
msgbus = "0x9Bb46D5100d2Db4608112026951c9C965b233f4D"
addgasestimateratio = 0.3

[[multichain]]
chainID = 314
name = "Filecoin"
gateway = "https://api.node.glif.io/rpc/v1"
blkinterval = 30
blkdelay = 1
forwardblkdelay = 100
maxblkdelta = 5000
cbridge = "0xd46f8e428a06789b5884df54e029e738277388d1"
otvault2 = "0x7d2db35cd885f10e73ef367d56bf43b617b740db"
ptbridge2 = "0xa7c9fede809b6af10dc52590804c69f40f6f8154"
msgbus = "0x317ed2054CCD6DC47d49550B4dE41589E7064154"

[[multichain]]
chainID = 7700
name = "Canto"
gateway = "https://canto.slingshot.finance/"
blkinterval = 30
blkdelay = 8
forwardblkdelay = 100
maxblkdelta = 5000
cbridge = "0xD46F8E428A06789B5884df54E029e738277388D1"
ptbridge2 = "0xa7C9FeDe809b6af10dC52590804c69F40f6f8154"

[[multichain]]
chainID = 1101
name = "Polygon zkEVM"
gateway = "https://zkevm-rpc.com"
blkinterval = 30
blkdelay = 6
forwardblkdelay = 200
maxblkdelta = 5000
cbridge = "0xD46F8E428A06789B5884df54E029e738277388D1"
msgbus = "0x9Bb46D5100d2Db4608112026951c9C965b233f4D"

[[multichain]]
accountprefix = "inj"
cbridge = "0xe559e36196b88f03423c2ee5708dd83b1d8505e7"
chainID = 999999997
gasadjustment = 1.5
gasprices = "50000000000inj"
gateway = "https://k8s.global.mainnet.tm.injective.network:443"
key = "injopr"
msgpackage = "cosmwasm.wasm.v1"
name = "Injective"
otvault = "0xa6214ccc545a3bfb979851b09debed43f124bf61"
ptbridge = "0x0ec4a924e58b579049c67979bfabb454424e74de"
rawchainid = "injective-1"
timeout = "10s"

